---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dotnetapi-develop-run-
  namespace: cicd
spec:
  params:
    - name: BUILD_TAG
      value: latest
    - name: EXT_REGISTRY
      value: docker.io
    - name: EXT_REGISTRY_NAMESPACE
      value: vccampbell
    - name: DOCKER_SECRET
      value: docker-io
    - name: GIT_REPO_URL
      value: https://github.com/vccampbell/s2i-dotnetcore-ex
    - name: GIT_REVISION
      value: develop
    - name: OC_CLI_VERSION
      value: "latest"
    - name: PIPELINE_RUN_URL
      value: https://console-openshift-console.apps-crc.testing/k8s/ns/cicd/tekton.dev~v1beta1~Pipeline/dotnetapi-develop
    - name: SKIP_PUSH
      value: "false"
    - name: TLSVERIFY
      value: "false"
    - name: WEBHOOK_URL_SECRET
      value: o365-webhook-url
    - name: WEBHOOK_URL_SECRET_KEY
      value: webhook-url
  pipelineRef:
    name: dotnetapi-develop
  serviceAccountName: pipeline
  workspaces:
    - name: shared-workspace
      subPath: source
      persistentvolumeclaim:
        claimName: dotnetapi-source-pvc
    - name: ssh-creds
      secret:
        secretName: github-ssh-private-key
    - name: images-url
      emptyDir: {}
